// react-project/src/components/Footer.tsx
import Ads from './Ads';

const Footer = () => {
  const isProd = import.meta.env.PROD;

  return (
    <>
      <img 
        className="counter hidden"
        src="https://count.getloli.com/@MFJip?name=MFJip&theme=booru-mjg&padding=7&offset=0&align=top&scale=1&pixelated=1&darkmode=auto"
        alt=""
      />
      {isProd ? (
        <footer data-footer className="footer">
          <span className="material-symbols-outlined"> location_on </span>
          <span> 广州 </span> | 
          <span> © 2025 MFJip612 </span> |
          <a href="https://icp.gov.moe/?keyword=20229994" target="_blank" rel="noopener noreferrer">萌ICP备20229994号</a> | 
          <a href="/sitemap.xml" target="_blank" rel="noopener noreferrer">网站地图</a> | 
          <a href="/rss.xml" target="_blank" rel="noopener noreferrer">RSS 订阅</a>
          <Ads />
        </footer>
      ) : (
        <footer data-footer className="footer">
          <span className="material-symbols-outlined"> location_on </span>
          <span> 广州 </span> | 
          <span> © 2025 MFJip612 </span> |
          <a href="https://icp.gov.moe/?keyword=20229994" target="_blank" rel="noopener noreferrer">萌ICP备20229994号</a>
          <Ads />
        </footer>
      )}
    </>
  );
};

export default Footer;

// src/components/Footer.vue
<template>
    <img class="counter"
        src="https://count.getloli.com/@MFJip?name=MFJip&theme=booru-mjg&padding=7&offset=0&align=top&scale=1&pixelated=1&darkmode=auto"
        alt="">
    <footer data-footer class="footer" v-if="isProd">
        <span class="material-symbols-outlined"> location_on </span><span> 广州 </span> | <span> © 2025 MFJip612
        </span> |
        <a href="https://icp.gov.moe/?keyword=20229994" target="_blank">萌ICP备20229994号</a> | <a href="/sitemap.xml"
            target="_blank" v-if="isProd">网站地图</a> | <a href="/rss.xml" target="_blank" v-if="isProd">RSS 订阅</a>
        <Ads></Ads>
    </footer>
    <footer data-footer class="footer" v-else>
        <span class="material-symbols-outlined"> location_on </span><span> 广州 </span> | <span> © 2025 MFJip612
        </span> |
        <a href="https://icp.gov.moe/?keyword=20229994" target="_blank">萌ICP备20229994号</a>
        <Ads></Ads>
    </footer>

</template>
<script setup>
import Ads from "./Ads.vue";

const isProd = import.meta.env.PROD;
</script>
<style scoped>
.footer {
    width: 100%;
    height: var(--footer-height);
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 1rem;
    box-shadow: 0 -0.125rem 0.5rem var(--color-shadow);
    background-color: var(--color-background);
    z-index: 999;
    /* position: absolute;
    left: 0;
    bottom: 0;
    margin-top: var(--footer-height); */
}

.counter {
    display: none;
    visibility: hidden;
}
</style>
