// src/routes/about/+page.svelte
<script>
	import Navbar from '$lib/components/Navbar.svelte';
	import Footer from '$lib/components/Footer.svelte';

	const skills = [
    { name: 'Python', level: 60 },
		{ name: 'TypeScript / JavaScript', level: 55 },
		{ name: 'CSS / Design Systems', level: 20 },
		{ name: 'C++', level: 20 },
		{ name: 'Cloudflare Workers', level: 15 },
		{ name: 'Go', level: 10 },
		{ name: 'Rust', level: 10 },
		{ name: 'Svelte / SvelteKit', level: 10 }
	];

	const timeline = [
		{
			year: '2024 — Now',
			title: 'Learning Javascript & TypeScript',
			desc: 'Developing my personal blog website, from the initial basic web page suite to the current SvelteKit.'
		},
		{
			year: '2022 — 2024',
			title: 'Learning Python & C++',
			desc: 'Learning Python, First Exposure to C++, wrote a few small tools via them.'
		},
		{
			year: '2020 — 2022',
			title: 'First time encountering Yi Language(易语言)',
			desc: 'Wrote a few small tools using Yi Language(易语言).'
		}
	];
</script>

<svelte:head>
	<title>About // MFJip612</title>
	<meta name="description" content="About MFJip612 - Engineer, builder, tinkerer." />
</svelte:head>

<div class="page-wrapper">
	<!-- Navigation -->
	<Navbar activePath="/about" />

	<!-- Page Header -->
	<header class="page-header">
		<div class="container">
			<div class="section-header">
				<h1>About</h1>
			</div>
			<p class="page-subtitle">System profile &amp; capabilities overview.</p>
		</div>
	</header>

	<!-- Main Content -->
	<main class="main-content">
		<div class="container">
			<!-- Bio Section -->
			<section class="bio-section">
				<div class="bio-grid">
					<div class="bio-avatar card">
						<div class="avatar-placeholder">
							<span class="avatar-initials">MF</span>
						</div>
					</div>
					<div class="bio-text card">
						<div class="card-body bio-body">
							<p class="bio-paragraph">
								I'm a software engineer who lives at the intersection of systems programming, web
								development, and design engineering. I care deeply about performance, developer
								experience, and building tools that respect the user's time.
							</p>
							<p class="bio-paragraph">
								Currently focused on edge computing, design systems at scale, and pushing what's
								possible in the browser. I believe in writing code that is fast, accessible, and a
								joy to work with.
							</p>
							<div class="bio-terminal code-block" style="margin-top: 1.25rem;">
								<span style="color: var(--color-secondary-container);">$</span> echo "Philosophy"
								<br />
								<span style="color: var(--color-on-surface);">
									&rarr; Ship early. Iterate often. Never stop learning.</span
								>
							</div>
						</div>
					</div>
				</div>
			</section>

			<!-- Skills Section -->
			<section class="skills-section" style="margin-top: 3rem;">
				<div class="section-header">
					<h2>Technical Proficiency</h2>
				</div>
				<div class="skills-grid card">
					<div class="card-body skills-body">
						{#each skills as skill (skill.name)}
							<div class="skill-row">
								<div class="skill-info">
									<span class="skill-name">{skill.name}</span>
									<span class="skill-percent">{skill.level}%</span>
								</div>
								<div class="skill-track">
									<div class="skill-fill" style="width: {skill.level}%;"></div>
									{#each Array(20) as _, i}
										<div class="skill-segment" class:active={(i / 20) * 100 <= skill.level}></div>
									{/each}
								</div>
							</div>
						{/each}
					</div>
				</div>
			</section>

			<!-- Timeline Section -->
			<section class="timeline-section" style="margin-top: 3rem;">
				<div class="section-header">
					<h2>Timeline</h2>
				</div>
				<div class="timeline-list">
					{#each timeline as item (item.year)}
						<div class="timeline-item card">
							<div class="timeline-marker"></div>
							<div class="timeline-content">
								<span class="timeline-year">{item.year}</span>
								<h3 class="timeline-title">{item.title}</h3>
								<p class="timeline-desc">{item.desc}</p>
							</div>
						</div>
					{/each}
				</div>
			</section>

			<!-- Contact Section -->
			<section class="contact-section" style="margin-top: 3rem;">
				<div class="section-header">
					<h2>Connect</h2>
				</div>
				<div class="contact-grid">
					<a
						href="https://github.com/MFJip612"
						target="_blank"
						rel="noopener noreferrer"
						class="contact-card card"
					>
						<div class="card-body contact-body">
							<span class="contact-icon">&lt;/&gt;</span>
							<span class="contact-label">GitHub</span>
							<span class="contact-handle">@MFJip612</span>
						</div>
					</a>
					<a href="/links" class="contact-card card">
						<div class="card-body contact-body">
							<span class="contact-icon">&#x26D3;</span>
							<span class="contact-label">Friend Links</span>
							<span class="contact-handle">View all &rarr;</span>
						</div>
					</a>
				</div>
			</section>
		</div>
	</main>

	<!-- Footer -->
	<Footer />
</div>

<style>
	.page-wrapper {
		position: relative;
		z-index: 1;
		min-height: 100vh;
		display: flex;
		flex-direction: column;
	}

	/* === Page Header === */
	.page-header {
		padding: 3rem 0 2rem;
		border-bottom: 1px solid var(--color-outline-variant);
	}

	.page-subtitle {
		margin-top: 0.5rem;
		color: var(--color-on-surface-variant);
		font-family: var(--font-code);
		font-size: var(--text-label-md);
	}

	/* === Main Content === */
	.main-content {
		flex: 1;
		padding: 3rem 0 4rem;
	}

	/* Bio Grid */
	.bio-grid {
		display: grid;
		grid-template-columns: 200px 1fr;
		gap: 1.5rem;
		align-items: start;
	}

	@media (max-width: 768px) {
		.bio-grid {
			grid-template-columns: 1fr;
			justify-items: center;
		}
	}

	.avatar-placeholder {
		aspect-ratio: 1;
		display: flex;
		align-items: center;
		justify-content: center;
		background: linear-gradient(
			135deg,
			var(--color-surface-container-high) 0%,
			var(--color-surface-container-low) 100%
		);
		border-radius: var(--radius-default);
	}

	.avatar-initials {
		font-family: var(--font-headline);
		font-size: 3rem;
		font-weight: 700;
		color: var(--color-primary);
		opacity: 0.8;
	}

	.bio-body {
		padding: 1.5rem;
	}

	.bio-paragraph {
		margin-bottom: 1rem;
		line-height: 1.7;
	}

	.bio-paragraph:last-of-type {
		margin-bottom: 0;
	}

	/* Skills */
	.skills-body {
		padding: 1.5rem;
	}

	.skill-row {
		margin-bottom: 1.25rem;
	}

	.skill-row:last-child {
		margin-bottom: 0;
	}

	.skill-info {
		display: flex;
		justify-content: space-between;
		align-items: baseline;
		margin-bottom: 0.375rem;
	}

	.skill-name {
		font-family: var(--font-headline);
		font-size: var(--text-label-md);
		font-weight: 500;
		color: var(--color-on-surface);
	}

	.skill-percent {
		font-family: var(--font-headline);
		font-size: 0.75rem;
		color: var(--color-outline);
	}

	.skill-track {
		display: flex;
		gap: 2px;
		height: 10px;
		position: relative;
	}

	.skill-segment {
		flex: 1;
		background-color: var(--color-outline-variant);
		border-radius: 1px;
		transition: background-color var(--transition-fast);
	}

	.skill-segment.active {
		background-color: var(--color-primary-container);
	}

	.skill-fill {
		position: absolute;
		inset: 0;
		background: linear-gradient(
			90deg,
			var(--color-primary-container),
			var(--color-secondary-container)
		);
		opacity: 0.15;
		border-radius: 1px;
	}

	/* Timeline */
	.timeline-list {
		display: flex;
		flex-direction: column;
		gap: 1rem;
		position: relative;
		padding-left: 1.5rem;
	}

	.timeline-list::before {
		content: '';
		position: absolute;
		left: 6px;
		top: 0;
		bottom: 0;
		width: 2px;
		background-color: var(--color-outline-variant);
	}

	.timeline-item {
		position: relative;
		padding: 1.25rem 1.5rem;
	}

	.timeline-marker {
		position: absolute;
		left: -1.5rem;
		top: 1.5rem;
		width: 14px;
		height: 14px;
		border-radius: var(--radius-full);
		background-color: var(--color-primary-container);
		border: 3px solid var(--color-background);
		box-shadow: 0 0 0 2px var(--color-primary-container);
	}

	.timeline-year {
		font-family: var(--font-headline);
		font-size: 0.6875rem;
		text-transform: uppercase;
		letter-spacing: 0.08em;
		color: var(--color-secondary-container);
		display: block;
		margin-bottom: 0.375rem;
	}

	.timeline-title {
		font-family: var(--font-headline);
		font-size: 1rem;
		font-weight: 600;
		color: var(--color-on-surface);
		margin-bottom: 0.375rem;
	}

	.timeline-desc {
		font-size: var(--text-body-md);
		color: var(--color-on-surface-variant);
		line-height: 1.6;
	}

	/* Contact Grid */
	.contact-grid {
		display: grid;
		grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
		gap: 1rem;
	}

	.contact-card {
		text-decoration: none;
		transition:
			border-color var(--transition-base),
			box-shadow var(--transition-base);
	}

	.contact-card:hover {
		border-color: var(--color-primary-container);
		box-shadow: var(--glow-primary);
	}

	.contact-body {
		display: flex;
		flex-direction: column;
		align-items: center;
		gap: 0.375rem;
		padding: 1.5rem 1rem;
		text-align: center;
	}

	.contact-icon {
		font-family: var(--font-headline);
		font-size: 1.5rem;
		color: var(--color-secondary-container);
	}

	.contact-label {
		font-family: var(--font-headline);
		font-size: var(--text-label-md);
		font-weight: 600;
		color: var(--color-on-surface);
		text-transform: uppercase;
		letter-spacing: 0.06em;
	}

	.contact-handle {
		font-size: 0.8125rem;
		color: var(--color-on-surface-variant);
	}

	@media (max-width: 767px) {
		.page-header {
			padding: 2rem 0 1.5rem;
		}
		.main-content {
			padding: 2rem 0 3rem;
		}
	}
</style>

// src/views/about/index.vue
<script setup lang="ts">
import { ref } from 'vue'
import { RouterLink } from 'vue-router'
import LayoutHeader from '@/components/LayoutHeader.vue'
import LayoutFooter from '@/components/LayoutFooter.vue'
import LucideIcon from '@/components/LucideIcon.vue'

interface SkillGroup {
  title: string
  items: string[]
}

const skillGroups: SkillGroup[] = [
  { title: 'Languages', items: ['Go', 'Rust', 'TypeScript', 'Python', 'C++'] },
  { title: 'Infrastructure', items: ['Kubernetes', 'Docker', 'Terraform', 'AWS', 'Linux'] },
  { title: 'Tools', items: ['Neovim', 'Git', 'Vim', 'tmux', 'Zsh'] }
]

interface TimelineEntry {
  period: string
  title: string
  description: string
}

const timeline: TimelineEntry[] = [
  {
    period: '2024 - 至今',
    title: 'Web学习 @ Intermediate',
    description: '从前端到后端，深入学习掌握Web开发技术栈'
  },
  {
    period: '2023 - 2024',
    title: '进一步学习 @ Greenhorn',
    description: '从Python到C++，深入理解系统编程'
  },
  {
    period: '2020 - 2023',
    title: '编程入门 @ Beginner',
    description: '从易语言开始'
  }
]

const backHovered = ref(false)
</script>

<template>
  <LayoutHeader />

  <main class="page-about">
    <!-- Page header -->
    <div class="about-header">
      <h2 class="geek-h2 about-header__title">关于我</h2>
      <RouterLink to="/" class="about-header__back"
        :style="{ color: backHovered ? 'var(--geek-brand-500)' : 'var(--geek-text-tertiary)' }" data-dom-id="back-home"
        @mouseenter="backHovered = true" @mouseleave="backHovered = false">&larr; Home</RouterLink>
    </div>

    <!-- Bio section -->
    <section class="about-section" aria-label="个人简介">
      <div class="about-prompt">
        <span class="about-prompt__dolar">$</span>
        <span class="about-prompt__cmd">cat about.md</span>
      </div>
      <div class="about-bio">
        <div class="about-bio__body">
          <p class="about-bio__lead">
            <span class="about-bio__accent">学生</span> /
            <span class="about-bio__accent">开源爱好者</span>
          </p>
          <p class="about-bio__text">
            喜欢探索新事物。
          </p>
          <p class="about-bio__text">
            常驻湾区，正在学习全栈开发。目前专注于后端架构设计与性能优化，同时对云原生技术、基础设施自动化保持浓厚兴趣。
          </p>
        </div>
      </div>
    </section>

    <!-- Skills section -->
    <section class="about-section" aria-label="技能">
      <h3 class="geek-h3 about-section__title">
        <span class="about-section__title-icon">&boxur;&boxvr;&boxdl;&nbsp;</span>技能树
      </h3>
      <div v-for="group in skillGroups" :key="group.title" class="about-skill">
        <p class="about-skill__label">{{ group.title }}</p>
        <div class="about-skill__row">
          <span v-for="item in group.items" :key="item" class="about-skill__badge">
            {{ item }}
          </span>
        </div>
      </div>
    </section>

    <!-- Experience timeline -->
    <section class="about-section" aria-label="经历">
      <h3 class="geek-h3 about-section__title">经历</h3>
      <div class="about-timeline">
        <div class="about-timeline__line" />
        <div v-for="(entry, idx) in timeline" :key="idx" class="about-timeline__entry">
          <span class="about-timeline__dot" />
          <p class="about-timeline__period">{{ entry.period }}</p>
          <p class="about-timeline__role">{{ entry.title }}</p>
          <p class="about-timeline__desc">{{ entry.description }}</p>
        </div>
      </div>
    </section>

    <!-- Contact section -->
    <section class="about-section" aria-label="联系">
      <div class="about-prompt">
        <span class="about-prompt__dolar">$</span>
        <span class="about-prompt__cmd">echo contact</span>
      </div>
      <div class="about-contact">
        <p class="about-contact__comment"># 找到我</p>
        <div class="about-contact__list">
          <a href="https://github.com/MFJip612" target="_blank" rel="noopener noreferrer" class="about-contact__link">
            <LucideIcon name="github" :size="16" />
            <span>github.com/MFJip612</span>
          </a>
          <a href="https://twitter.com/mfjip612" target="_blank" rel="noopener noreferrer" class="about-contact__link">
            <LucideIcon name="twitter" :size="16" />
            <span>@mfjip612</span>
          </a>
          <a href="mailto:contact@waterspo.top" class="about-contact__link">
            <LucideIcon name="mail" :size="16" />
            <span>contact@waterspo.top</span>
          </a>
        </div>
      </div>
    </section>
  </main>

  <LayoutFooter />
</template>

<style scoped>
.page-about {
  max-width: 960px;
  margin: 0 auto;
  padding: var(--geek-space-2xl) 24px var(--geek-space-3xl);
  min-height: calc(100vh - 64px - 120px);
}

.about-header {
  display: flex;
  align-items: center;
  gap: 16px;
  margin-bottom: 32px;
}

.about-header__title {
  margin: 0;
  text-wrap: balance;
  word-break: keep-all;
  overflow-wrap: break-word;
}

.about-header__back {
  font-family: var(--geek-font-mono);
  font-size: var(--geek-text-sm);
  text-decoration: none;
  transition: color 120ms cubic-bezier(0.2, 0.8, 0.2, 1);
}

/* ── Section ─────────────────────────────────────────── */
.about-section {
  margin-bottom: 48px;
}

.about-section__title {
  font-family: var(--geek-font-mono);
  text-wrap: balance;
  word-break: keep-all;
  margin: 0 0 24px 0;
}

.about-section__title-icon {
  color: var(--geek-text-tertiary);
}

/* ── Terminal prompt ─────────────────────────────────── */
.about-prompt {
  font-family: var(--geek-font-mono);
  font-size: var(--geek-text-sm);
  color: var(--geek-brand-500);
  margin-bottom: var(--geek-space-md);
  user-select: none;
}

.about-prompt__dolar {
  color: var(--geek-text-tertiary);
}

/* ── Bio block ───────────────────────────────────────── */
.about-bio {
  background: var(--geek-code-bg);
  border: 1px solid var(--geek-border);
  border-radius: var(--geek-radius-md);
  padding: var(--geek-space-xl);
}

.about-bio__body {
  font-family: var(--geek-font-body);
  font-size: var(--geek-text-base);
  line-height: var(--geek-leading-relaxed);
  color: var(--geek-code-text);
}

.about-bio__body p {
  margin: 0;
}

.about-bio__body p+p {
  margin-top: 16px;
}

.about-bio__lead {
  margin-bottom: 16px !important;
}

.about-bio__accent {
  color: var(--geek-brand-500);
}

.about-bio__lead .about-bio__accent:first-child {
  font-weight: var(--geek-weight-semibold);
}

.about-bio__text {
  margin-top: 16px;
}

/* ── Skills ──────────────────────────────────────────── */
.about-skill {
  margin-bottom: 20px;
}

.about-skill:last-child {
  margin-bottom: 0;
}

.about-skill__label {
  font-family: var(--geek-font-mono);
  font-size: var(--geek-text-xs);
  color: var(--geek-text-tertiary);
  text-transform: uppercase;
  letter-spacing: 0.05em;
  margin: 0 0 12px 0;
}

.about-skill__row {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
}

.about-skill__badge {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  font-family: var(--geek-font-mono);
  font-size: var(--geek-text-sm);
  color: var(--geek-code-text);
  background: var(--geek-code-bg);
  border: 1px solid var(--geek-border);
  border-radius: var(--geek-radius-sm);
  padding: 4px 12px;
  transition:
    border-color 120ms cubic-bezier(0.2, 0.8, 0.2, 1),
    background 120ms cubic-bezier(0.2, 0.8, 0.2, 1);
  cursor: default;
}

.about-skill__badge:hover {
  border-color: var(--geek-brand-500);
  background: var(--geek-surface);
}

/* ── Timeline ────────────────────────────────────────── */
.about-timeline {
  position: relative;
  padding-left: var(--geek-space-xl);
}

.about-timeline__line {
  position: absolute;
  top: 0;
  bottom: 0;
  left: 5px;
  width: 1px;
  background: var(--geek-border);
}

.about-timeline__entry {
  position: relative;
  margin-bottom: 32px;
}

.about-timeline__entry:last-child {
  margin-bottom: 0;
}

.about-timeline__dot {
  position: absolute;
  left: calc(-1 * var(--geek-space-xl) + 1px);
  top: 6px;
  width: 10px;
  height: 10px;
  border-radius: var(--geek-radius-full);
  background: var(--geek-brand-500);
}

.about-timeline__period {
  font-family: var(--geek-font-mono);
  font-size: var(--geek-text-sm);
  color: var(--geek-brand-500);
  margin: 0 0 4px 0;
}

.about-timeline__role {
  font-family: var(--geek-font-body);
  font-size: var(--geek-text-base);
  font-weight: var(--geek-weight-semibold);
  color: var(--geek-text-primary);
  margin: 0 0 4px 0;
}

.about-timeline__desc {
  font-family: var(--geek-font-body);
  font-size: var(--geek-text-sm);
  color: var(--geek-text-secondary);
  margin: 0;
}

/* ── Contact ─────────────────────────────────────────── */
.about-contact {
  background: var(--geek-code-bg);
  border: 1px solid var(--geek-border);
  border-radius: var(--geek-radius-md);
  padding: var(--geek-space-lg);
}

.about-contact__comment {
  font-family: var(--geek-font-mono);
  font-size: var(--geek-text-xs);
  color: var(--geek-text-tertiary);
  margin: 0 0 var(--geek-space-md) 0;
}

.about-contact__list {
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.about-contact__link {
  display: inline-flex;
  align-items: center;
  gap: var(--geek-space-sm);
  font-family: var(--geek-font-mono);
  font-size: var(--geek-text-sm);
  color: var(--geek-code-text);
  text-decoration: none;
  transition: color 120ms cubic-bezier(0.2, 0.8, 0.2, 1);
}

.about-contact__link:hover {
  color: var(--geek-brand-500);
  text-decoration: underline;
  text-underline-offset: 2px;
}
</style>
