// src/components/Navbar.vue
<script setup>
import {
    NavigationMenu,
    NavigationMenuContent,
    NavigationMenuIndicator,
    NavigationMenuItem,
    NavigationMenuLink,
    NavigationMenuList,
    NavigationMenuTrigger,
    NavigationMenuViewport,
    navigationMenuTriggerStyle
} from '@/components/ui/navigation-menu'
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar'
import ModeToggle from "@/components/ModeToggle.vue";
import Logo from "@/assets/images/logo.jpg";

const pages = import.meta.glob('/src/views/**/page.ts', {
    eager: true,
    import: 'default'
});

const routes = Object.entries(pages)
    .map(([filePath, meta]) => {
        const routePath = filePath
            .replace('/src/views', '')
            .replace('/page.ts', '') || '/';
        return {
            path: routePath === '' ? '/' : routePath,
            meta,
        };
    })
    .filter(route => !route.meta?.hidden)
    .sort((a, b) => {
        const orderA = a.meta?.menuOrder ?? 9999;
        const orderB = b.meta?.menuOrder ?? 9999;
        return orderA - orderB;
    });
</script>
<template>
    <header
        class="fixed top-0 left-0 w-full h-(--header-height) bg-background/80 backdrop-blur-sm z-50 flex items-center px-4 shadow-md">
        <nav>
            <NavigationMenu>
                <NavigationMenuList>
                    <NavigationMenuItem class="flex justify-start">
                        <Avatar class="w-10 h-10 cursor-pointer">
                            <AvatarImage :src="Logo" />
                            <AvatarFallback>CN</AvatarFallback>
                        </Avatar>
                        <!-- <img v-bind:src="Logo" alt="Logo"> -->
                    </NavigationMenuItem>
                    <NavigationMenuItem v-for="route in routes" :key="route.path" class="flex justify-end">
                        <NavigationMenuLink as-child :class="navigationMenuTriggerStyle()">
                            <a :href="route.path">{{ route.meta.title }}</a>
                        </NavigationMenuLink>
                    </NavigationMenuItem>
                    <NavigationMenuItem>

                        <ModeToggle />

                    </NavigationMenuItem>
                </NavigationMenuList>
            </NavigationMenu>

        </nav>
    </header>
</template>
<style scoped></style>

// react-project/src/components/Navbar.tsx
import { Link } from 'react-router-dom';
import { memo } from 'react';
import ModeToggle from './ModeToggle';

// 模拟页面数据
const routes = [
  { path: '/', meta: { title: 'Home', menuOrder: 0 } },
  { path: '/about', meta: { title: 'About', menuOrder: 1 } },
  { path: '/article', meta: { title: 'Articles', menuOrder: 2 } },
  { path: '/shows', meta: { title: 'Shows', menuOrder: 3 } },
  { path: '/friends', meta: { title: 'Friends', menuOrder: 4 } }
];

const Navbar = () => {
  return (
    <header className="fixed top-0 left-0 w-full h-16 bg-background/80 backdrop-blur-sm z-50 flex items-center px-4 shadow-md">
      <nav>
        <ul className="flex space-x-6 items-center">
          <li className="flex justify-start">
            <Link to="/" className="flex items-center">
              <div className="w-10 h-10 rounded-full overflow-hidden">
                <img 
                  src="/favicon.svg" 
                  alt="Logo" 
                  className="w-full h-full object-cover"
                  loading="lazy"
                />
              </div>
            </Link>
          </li>
          {routes.map((route) => (
            <li key={route.path} className="flex justify-end">
              <Link 
                to={route.path} 
                className="text-gray-600 dark:text-gray-300 hover:text-blue-600 dark:hover:text-blue-400 px-2 py-1 rounded"
              >
                {route.meta.title}
              </Link>
            </li>
          ))}
          <li>
            <ModeToggle />
          </li>
        </ul>
      </nav>
    </header>
  );
};

export default memo(Navbar);
