// src/components/Footer.vue
<template>
    <footer class="footer">
        <span class="material-symbols-outlined"> location_on </span><span> 广州 </span> | <span> © 2025 MFJip612 </span> |
        <a href="https://icp.gov.moe/?keyword=20229994" target="_blank">萌ICP备20229994号</a>
    </footer>
</template>
<style scoped>
.footer {
    width: 100%;
    height: var(--footer-height);
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 1rem;
    box-shadow: 0 -0.125rem 0.5rem var(--color-shadow);
    background-color: var(--color-background);
    z-index: 999;
    /* position: absolute;
    left: 0;
    bottom: 0;
    margin-top: var(--footer-height); */
}
</style>

// src/lib/components/Footer.svelte
<script>
  let { text = 'Built with Precision, Made with ♥' } = $props();
</script>

<footer class="site-footer">
  <div class="container footer-inner">
    <div class="footer-left">
      <span class="footer-brand">&gt;_ MFJip612</span>
      <span class="footer-sep">//</span>
      <span class="footer-text">{text}</span>
    </div>
    <div class="footer-right">
      <span class="footer-status">
        <span class="status-dot"></span>
        All systems operational
      </span>
    </div>
  </div>
</footer>

<style>
  .site-footer {
    border-top: 1px solid var(--color-outline-variant);
    padding: 1.5rem 0;
    background-color: var(--color-surface-container-lowest);
    margin-top: auto;
  }

  .footer-inner {
    display: flex;
    justify-content: space-between;
    align-items: center;
    flex-wrap: wrap;
    gap: 1rem;
  }

  .footer-left {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    font-family: var(--font-headline);
    font-size: 0.8125rem;
  }

  .footer-brand {
    color: var(--color-primary);
    font-weight: 600;
  }

  .footer-sep {
    color: var(--color-outline-variant);
  }

  .footer-text {
    color: var(--color-on-surface-variant);
  }

  .footer-right {
    font-family: var(--font-headline);
    font-size: 0.75rem;
    color: var(--color-on-surface-variant);
    display: flex;
    align-items: center;
    gap: 0.375rem;
  }

  .status-dot {
    width: 6px;
    height: 6px;
    border-radius: var(--radius-full);
    background-color: #28c840;
    box-shadow: 0 0 6px rgba(40, 200, 64, 0.5);
  }

  @media (max-width: 767px) {
    .footer-inner {
      flex-direction: column;
      text-align: center;
    }
  }
</style>
